### PR TITLE
Update N3b.csv

### PR DESCRIPTION
**Pull request by JPatruno**
Latest date updated.

### CODE REVIEW

**Comment by Schpidi** [comment]
@JPatruno it seems this one new line is a mix between TSM and Chl-a, aoi-id and coordinates from Chl-a but text from TSM. Could you please check? Thanks

**Comment by JPatruno** [comment]
> @JPatruno it seems this one new line is a mix between TSM and Chl-a, aoi-id and coordinates from Chl-a but text from TSM. Could you please check? Thanks

Hi @Schpidi yes I see now this difference in coordinates and AOI ID. I did not remember we have different coordinates and AOIs for Venice (I think I've always used same coordinates both for Chl and TSM). Anyway, if now we implement this change in coordinates and AOIs for differentiating Chl data and TSM data, I take note and I will share this with the CNR team, which is not aware of this change yet. Will you update coordinates and AOI for the new line? 
Thank you

**Comment by Schpidi** [comment]
we can't use the same coordinates and aoi-id as it would be just one poi. in which direction do you want me to adjust the new line? is it chl-a or tsm?

**Comment by JPatruno** [comment]
> we can't use the same coordinates and aoi-id as it would be just one poi. in which direction do you want me to adjust the new line? is it chl-a or tsm?

@Schpidi It is a tsm. Thank you

**Review by Schpidi — APPROVED** [review]

**Pull request merged**
