### PR TITLE
Updated e1a to 20200910

### PR DESCRIPTION
**Pull request by AlessandroScremin**
Updated e1a to 20200910

### CODE REVIEW

**Comment by Schpidi** [comment]
@AlessandroScremin I fixed the aoi_id of the new entries to be aligned with the previous ones. I propose to move E1a to the GeoDB next to harmonize with E1 which is already taken from GeoDB. What do you think?

**Review by Schpidi — APPROVED** [review]

**Comment by AlessandroScremin** [comment]
@gobaRules @gmilcinski 

I'm trying to import E1a and E2 into GeoDB, but I got an error on Validation cell...(gpd_data["data_provider"] = gpd_data.pop("provider")
gpd_data.head())

with the following error:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2645             try:
-> 2646                 return self._engine.get_loc(key)
   2647             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'provider'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-24-d0ba35a5e253> in <module>
----> 1 gpd_data["data_provider"] = gpd_data.pop("provider")
      2 gpd_data.head()

/opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/pandas/core/generic.py in pop(self, item)
    788         3  monkey        NaN
    789         """
--> 790         result = self[item]
    791         del self[item]
    792         try:

/opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/geopandas/geodataframe.py in __getitem__(self, key)
    544         GeoDataFrame.
    545         """
--> 546         result = super(GeoDataFrame, self).__getitem__(key)
    547         geo_col = self._geometry_column_name
    548         if isinstance(key, string_types) and key == geo_col:

/opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2798             if self.columns.nlevels > 1:
   2799                 return self._getitem_multilevel(key)
-> 2800             indexer = self.columns.get_loc(key)
   2801             if is_integer(indexer):
   2802                 indexer = [indexer]

/opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2646                 return self._engine.get_loc(key)
   2647             except KeyError:
-> 2648                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2649         indexer = self.get_indexer([key], method=method, tolerance=tolerance)
   2650         if indexer.ndim > 1 or indexer.size > 1:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'provider'

Could you please advice?

**Comment by gobaRules** [comment]
> @gobaRules @gmilcinski
> 
> I'm trying to import E1a and E2 into GeoDB, but I got an error on Validation cell...(gpd_data["data_provider"] = gpd_data.pop("provider")
> gpd_data.head())
> 
> ## with the following error:
> KeyError Traceback (most recent call last)
> /opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
> 2645 try:
> -> 2646 return self._engine.get_loc(key)
> 2647 except KeyError:
> 
> pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()
> 
> pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()
> 
> pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()
> 
> pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()
> 
> KeyError: 'provider'
> 
> During handling of the above exception, another exception occurred:
> 
> KeyError Traceback (most recent call last)
> in
> ----> 1 gpd_data["data_provider"] = gpd_data.pop("provider")
> 2 gpd_data.head()
> 
> /opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/pandas/core/generic.py in pop(self, item)
> 788 3 monkey NaN
> 789 """
> --> 790 result = self[item]
> 791 del self[item]
> 792 try:
> 
> /opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/geopandas/geodataframe.py in **getitem**(self, key)
> 544 GeoDataFrame.
> 545 """
> --> 546 result = super(GeoDataFrame, self).**getitem**(key)
> 547 geo_col = self._geometry_column_name
> 548 if isinstance(key, string_types) and key == geo_col:
> 
> /opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/pandas/core/frame.py in **getitem**(self, key)
> 2798 if self.columns.nlevels > 1:
> 2799 return self._getitem_multilevel(key)
> -> 2800 indexer = self.columns.get_loc(key)
> 2801 if is_integer(indexer):
> 2802 indexer = [indexer]
> 
> /opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
> 2646 return self._engine.get_loc(key)
> 2647 except KeyError:
> -> 2648 return self._engine.get_loc(self._maybe_cast_indexer(key))
> 2649 indexer = self.get_indexer([key], method=method, tolerance=tolerance)
> 2650 if indexer.ndim > 1 or indexer.size > 1:
> 
> pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()
> 
> pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()
> 
> pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()
> 
> pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()
> 
> KeyError: 'provider'
> 
> Could you please advice?

Hi @AlessandroScremin ,

the command which results in an error tries to rename a column called "provider" in your data to "data_provider". I am guessing "data_provider" is already in your data. I suggest you run `gpd_data.head()` and check if one of the column names is "data_provider". 
If this is the case simply skip ` gpd_data["data_provider"] = gpd_data.pop("provider")` command and continue with importing.

If this is not the case, I would need more information such as:
- with which Jupyter notebook you work
- the sample of the file you try to import

**Comment by AlessandroScremin** [comment]
@gobaRules 

Ok now it worked E1a adn E2 ingested into geoDB....
thnaks for the support

kr

Alessandro

**Pull request merged**
