### PR TITLE
Integrate e13d and other updates

### PR DESCRIPTION
**Pull request by lubojr**
- adds new indicator E13d - config, data, geojsons
- local geojson features will from now on be in separate directories by indicator type
- filled seconds to filenames on E1, E1a, E2 to match what data references, deleted orphaned geojsons
- possible to completely turn off map layers for indicator by setting `mapLayerEnable: false` in `indicatorsDefinition` (done for E13d)
missing: 
- [ ] E13d story

### CODE REVIEW

**Comment by aapopescu** [comment]
@lubojr, looks good, but I noticed the detections do not correspond with the image dates
any ideas why?
cc: @AlessandroScremin 

Screen Shot 2020-10-23 at 16 50 24

**Comment by AlessandroScremin** [comment]
@aapopescu  @lubojr 

Just  to be sure i checked all these for Vienna Airports area...

the records in the geojson have the sentinel 2 reference on EDC...both date hh:mm:ss

 "2020\/09\/02 10:07:20",
 "2020\/09\/02 10:07:20",
 "2020\/09\/02 10:07:20",
 "2020\/09\/02 10:07:20",
 "2020\/09\/02 10:07:24",
 "2020\/09\/02 10:07:24",
 "2020\/09\/07 10:07:18",
 "2020\/09\/07 10:07:18",
 "2020\/09\/07 10:07:22",
 "2020\/09\/09 09:57:22",
 "2020\/09\/09 09:57:22",
 "2020\/09\/09 09:57:25",
 "2020\/09\/09 09:57:25",
 "2020\/09\/09 09:57:25",
 "2020\/09\/09 09:57:25",
 "2020\/09\/12 10:07:19",
 "2020\/09\/12 10:07:19",
 "2020\/09\/12 10:07:19",
 "2020\/09\/12 10:07:19",
 "2020\/09\/12 10:07:19",
 "2020\/09\/12 10:07:19",
 "2020\/09\/12 10:07:23",
 "2020\/09\/14 09:57:21",
 "2020\/09\/14 09:57:21",
 "2020\/09\/14 09:57:21",
 "2020\/09\/14 09:57:21",
 "2020\/09\/14 09:57:21",
 "2020\/09\/14 09:57:21",
 "2020\/09\/14 09:57:21",
 "2020\/09\/14 09:57:24",
 "2020\/09\/14 09:57:24",
 "2020\/09\/14 09:57:24",


I think you are taking the date from csv (2020-09-01) but as it is monthly it is not correct...you should  take the image reference from the timestamp in the geojson...

**Comment by lubojr** [comment]
This indicator is monthly. A single geojson contains detections for whole month. Therefore time entries list contains months (from csv), they only are formatted to contain a day too. 

On the other side, if we want to show individual timestamps from geojsons as timeentries for the map and then match sentinel 2 images with the individual detections (their time), - please confirm @aapopescu @AlessandroScremin We will need to implement that. Up until now, timeentries were taken only from internal data or completely custom list (N4). Thanks

**Comment by aapopescu** [comment]
> This indicator is monthly. A single geojson contains detections for whole month. Therefore time entries list contains months (from csv), they only are formatted to contain a day too.
> 
> On the other side, if we want to show individual timestamps from geojsons as timeentries for the map and then match sentinel 2 images with the individual detections (their time), which would be probably the best way to go - please confirm @aapopescu @AlessandroScremin
> From dashboard point of view, we will need to implement that, as it will mean fetching the times from 2 sources, which have a different meaning. First individual months, that are used for charts and populate the list of entries for the map (and determines the date of a fetched geojson with detections). And second, individual timestamps from those detecions geojsons. Up until now, timeentries were taken only from internal data or completely custom list (N4). Should we proceed in implementing this special handling?

@lubojr, @AlessandroScremin, better to show the detections per date, to make sure we do not paint a wrong picture.

**Review by aapopescu — APPROVED** [review]

**Review by Schpidi — APPROVED** [review]

**Pull request merged**
