### PR TITLE
Iceeye

### PR DESCRIPTION
**Pull request by lubojr**
- Following Iceeye POIs have been added FR16_E11 NL3-E3 PL7_E11a UK9_E12b ES17_E13b DE18_E13b

- [x] Needs a story and validation @aapopescu 

- closes https://github.com/eurodatacube/eodash-data/issues/222

### CODE REVIEW

**Comment by aapopescu** [comment]
1. EO data shows black on PL7 POI:   https://eodash-testing.eox.at/iceeye/?indicator=E11a&poi=PL7-E11a 

2. Change Indicator description to: "Ports: throughput" for: https://eodash-testing.eox.at/iceeye/?indicator=E12b&poi=UK12-E12b

3. Change Indicator description to: "Oil Storage Volume" for: https://eodash-testing.eox.at/iceeye/?indicator=E3&poi=NL3-E3
4.  Remove https://eodash-testing.eox.at/iceeye/?indicator=E7&poi=ES18-E7 ---> we will use the picture in the story for the Finished goods production 
5. For all POIs, can we have S2 cloudless layer as default background?

**Comment by lubojr** [comment]
Resolved 2,3,5 (deleted), 6
Checked upon 1 and it looks like somehow miss configured rendering on EDC - not completely black (time is set correctly on client), some shades of grey can be seen - see attachment. 

iceeye-e11a

**Comment by aapopescu** [comment]
> Resolved 2,3,5 (deleted), 6
> Checked upon 1 and it looks like somehow miss configured rendering on EDC - not completely black (time is set correctly on client), some shades of grey can be seen - see attachment.
> 
> iceeye-e11a

@AlessandroScremin can you check please?

**Comment by AlessandroScremin** [comment]
@lubojr @aapopescu 

Ok was a parameter issue....now fixed

> > Resolved 2,3,5 (deleted), 6
> > Checked upon 1 and it looks like somehow miss configured rendering on EDC - not completely black (time is set correctly on client), some shades of grey can be seen - see attachment.
> > iceeye-e11a
> 
> @AlessandroScremin can you check please?

**Comment by aapopescu** [comment]
All updates done!

**Review by aapopescu — APPROVED** [review]

**Pull request merged**
