### PR TITLE
[WIP] Unify indicators

### LINKED ISSUE #500: Unify Indicators provided by different Agencies
into a single view

Currently:
- Multiple entries in the table and on map for the same indicator, e.g. North Adriatic – Chl-a 
maps

Aim:
- A single entry in the table and on map per indicator 

Example:
In the new visualisation, we would have a 
single entry for NorthAdriatic – Chl maps in 
the table.

We could distinguish between data coming from different agencies by implementing different tabs (on top of indicator data map).

### PR DESCRIPTION
**Pull request by silvester-pari**
closes #500

### CODE REVIEW

**Comment by aapopescu** [comment]
can we change the sub-title when we move from one tab to the other?
for example here we have NASA map active but text is about ESA

Screen Shot 2020-09-30 at 16 48 58

**Comment by silvester-pari** [comment]
ah, you're right - this worked before when the whole indicator was replaced (but the timeline position was not saved), with the newest changes this does not change any more. i will fix this quickly.

**Comment by silvester-pari** [comment]
this is now fixed:
image

however, there seems to be a problem with the tab order when switching away (eg other indicator) and back; will need to investigate why this happens.

**Comment by aapopescu** [comment]
> this is now fixed:
> image
> 
> however, there seems to be a problem with the tab order when switching away (eg other indicator) and back; will need to investigate why this happens.

I keep seeing the same behaviour:
Screen Shot 2020-10-01 at 08 51 45
Screen Shot 2020-10-01 at 08 52 03

**Pull request merged**
