### PR TITLE
feat: add 5 new biomass datasets from VEDA

### PR DESCRIPTION
**Pull request by lubojr**
https://github.com/eurodatacube/eodash/issues/2392

### CODE REVIEW

**Comment by aapopescu** [comment]
- something must be wrong with this dataset because there is no variability across datasets, please double check https://eodash-trilateral-testing.eox.at/adding-biomass-data/explore?search=World%3A+Evapotranspiration+-+LIS+10km+Global+DA&x=-974930.96041&y=3522155.28638&z=2.49185&poi=World-LIS_Global_DA_Evap

**Review by aapopescu — CHANGES_REQUESTED** [review]
- Datasets are duplicated and with different names in the search bar https://eodash-trilateral-testing.eox.at/adding-biomass-data/explore?search=Daily+emissions+from+sector+5+from+forest+fires.&x=2032967.56947&y=1242175.13535&z=2.62076 
- some dates are formatted strangely, with a "-" https://eodash-trilateral-testing.eox.at/adding-biomass-data/explore?search=World%3A+Normalized+difference+vegetation+index+from+HLS&x=-9102909.3032&y=3083293.78867&z=10.3282&poi=World-HLS_NDVI
- indicator names need to be revised
@AlessandroScremin , can you please also review?

**Comment by lubojr** [comment]
@aapopescu thank you very much for the feedback.

- fixed the LIS_Global_DA_Evap - the scaling parameter was wrong
- updated the preliminary indicator names and indicator codes, grouping the 3 EPA indicators into one indicator code `EPA`, so the number of entries in search will be smaller (1 for indicator level and 3 for different "pois" - in our case collections)
- fixed the extra `-` in the date labels
- the links are updated in the original issue https://github.com/eurodatacube/eodash/issues/2392#issuecomment-2015477594

**Comment by aapopescu** [comment]
Thanks, @lubojr 

- can we get the chart feature on this one? https://eodash-trilateral-testing.eox.at/adding-biomass-data/explore?search=World%3A+Evapotranspiration%2C+LIS&x=0&y=-465988.56611&z=3.74819&poi=World-LIS_Global_DA_Evap

**Comment by lubojr** [comment]
@aapopescu Technically yes, I tried to integrate it already, but the dataset is huge (daily data for 19 years), so the statistics endpoint was too overloaded. NASA analytics endpoint does not allow "under-the-hood" time axis aggregation like Sentinel Hub can does, so we would need to pick up dates ourselves to fetch the statistics for manually. We have observed the "reasonable" limit in the past being a few hundred of requests to the statistics at one go.

We saw now that the data is quite dynamic and it seems to have some peaks that could be a pity to miss.

We would propose to do a custom implementation for a 1 year history from the currently selected date on the main map.
Or do you have any specific date range in mind which could be interesting for this dataset? E.g. first day of a month for full 19 years (ignoring the possible spikes), or weekly for last x years of duration or so? 

Ideally we should let the user pick this interval/time start/end time/aggregation for custom chart themselves, but it would be more involved development, that should probably not go into the current implementation of the v4 version of the client.

**Comment by lubojr** [comment]
@aapopescu We have implemented the above mentioned solution of showing always 1 year history from currently selected date on the main map. This is also enabled for every other NASA statistics API dataset (previously we were only using the newest several hundred times).
From our point of view the PR could be merged. Could you please confirm if the indicator names and such are now fine to be deployed?

**Comment by lubojr** [comment]
I am merging this PR in order to avoid possible merge conflicts upstream and to have this available in new trilateral stories. We can still do updates afterwards.

**Pull request merged**
