### PR TITLE
chore: add extreme events theme

### PR DESCRIPTION
**Pull request by lubojr**
- icon: `mdi-lightning-bolt` 
image
- description on story page: `Tracking the Effects of Extreme Events`
- title: `Extreme Events`
- story page has no special "image" yet
- color: #a1280a

https://eodash-trilateral-testing.eox.at/extreme-events-theme/

closes https://github.com/eurodatacube/eodash/issues/2603

### CODE REVIEW

**Comment by aapopescu** [comment]
Thanks, @lubojr, assuming the colour chosen is from the same palette as the rest, it is OK but please change the name to "EXTREMES". All other themes are just 1 word.

Also, what is the "special image"?

**Comment by lubojr** [comment]
@aapopescu Thank you. Changed name accordingly.

This is the image that I mentioned about that is configurable (stories view).
image

**Comment by lubojr** [comment]
Expecting a final approval and we can merge the VIIRS fires? https://github.com/eurodatacube/eodash/pull/2614


First dataset would be

**Comment by lubojr** [comment]
Merging into [VIIRS_SNPP_2023](https://github.com/eurodatacube/eodash/tree/VIIRS_SNPP_2023)

**Pull request merged**
