### PR TITLE
Csv export

### PR DESCRIPTION
**Pull request by santilland**

### CODE REVIEW

**Comment by santilland** [comment]
Currently the following values are being exported, i think these are the most useful ones, as well as the ones that usually have content:

time, measurement, indicatorValue, referenceTime, referenceValue, dataProvider, eoSensor, colorCode, inputData

**Comment by aapopescu** [comment]
> Currently the following values are being exported, i think these are the most useful ones, as well as the ones that usually have content:
> 
> time, measurement, indicatorValue, referenceTime, referenceValue, dataProvider, eoSensor, colorCode, inputData

We should include also the AOI and City

**Comment by santilland** [comment]
Maybe we can add the AOI and City name somehow to the filename? As this would be an equal value for every row it seems to be increasing the size of the csv unnecessarily.
Although the AOI might be a bit difficult to write in the file name as we would need maybe to use points or commas... so not sure.
I will add the AOI to the csv and the city name to the file name for now.
Let me know what you think.

**Comment by santilland** [comment]
So now the file name is:
<cityname>_<downloadday>_<countrycode>-<indicatorcode>.csv
E.g.:
Vilnius_2020-11-17_LT-N1.csv

**Review by aapopescu — APPROVED** [review]

**Pull request merged**
