### PR TITLE
Merging updates through October 8, 2020

### PR DESCRIPTION
**Pull request by bricegrunert**

### CODE REVIEW

**Comment by Schpidi** [comment]
@aapopescu do you want us to integrate the NY data? Should be straightforward to add to the overall N3b file https://github.com/eurodatacube/eodash/blob/staging/app/public/data/trilateral/N3b.csv.

**Comment by aapopescu** [comment]
> @aapopescu do you want us to integrate the NY data? Should be straightforward to add to the overall N3b file https://github.com/eurodatacube/eodash/blob/staging/app/public/data/trilateral/N3b.csv.

@bricegrunert yes please

**Comment by Schpidi** [comment]
I'm currently merging the data into our N3b.csv and realized, that the SPM values for NAS are quite different than the ones we have currently. E.g. 2019-01-11T12:40:00 has currently -19.13898213 but the new value is -8.090164703. I'm not sure if I should update the data? @bricegrunert could you please confirm which values are the correct ones? Thanks

**Comment by Schpidi** [comment]
I've integrated the new data and also new values now (see https://github.com/eurodatacube/eodash/blob/staging/app/public/data/trilateral/N3b.csv). Please advice if I should revert to the old values (see previous comment).

Please note that I had to apply a couple of fixes like adjusting the non-existent 2019-02-29 to 2019-02-28, adding padding 0 to the hours e.g. 05 instead of just 5, etc.

**Comment by bricegrunert** [comment]
@Schpidi Terrific thank you. The new values are correct - there was a slight error in the original code that I corrected. I will adjust the dates/padding hours moving forward, thanks much.

Do you prefer new files for each update, or revising the old files? I put in the last updates under a different date, to avoid creating confusion while we caught up on the old updates. Thanks!

**Comment by Schpidi** [comment]
@bricegrunert great, thanks for confirming. In the end I need to merge everything in a single N3b.csv file anyway, so revising the old files should be fine. I close this PR now since all values are copied over. Thanks

**Pull request closed without merging**
