### PR TITLE
Gtif admin custom area

### PR DESCRIPTION
**Pull request by lubojr**
- cleaner handling of admin borders used to get custom chart

### CODE REVIEW

**Comment by lubojr** [comment]
@patrick-griffiths Could you please review current state of this PR on https://gtif-testing.eox.at/gtif_admin_custom_area/ and give us feedback? 

This PR brings in a new Info Panel in right Data Panel in explore mode with more information for the user that certain admin zones are meant to be clickable to fetch custom time series (and hides the draw tools in the map)

Currently enabled for these datasets:
```
Gemeinde: AQA, AQB, AQC, MOBI1
Zählsprengel: SOL1, SOL2 
```

**Comment by patrick-griffiths** [comment]
@lubojr this looks nice, has a few glitches in terms of text layout, but certainly a step forward!~

would be good to understand and discuss the current limitation (i.e. could this be used for the hydro reservoir data). 

In addition, we should do a few improvements on the admin aggregated mobility data: 
- make these 25-50% transparent 
- could the time series zoom into e.g. 5-10 day intervals? currently it visualizes a very long time series which does not look inviting 
- could we show (as a optional baselayer) OSM road/train networks (or the full OSM map features)?  

Maybe we discuss these separately and create a dedicated issue?

**Comment by lubojr** [comment]
@patrick-griffiths Could you please tell me concrete examples of the text-layout which need to be changed? 

As per the individual points:

0) As we currently have just 1 reservoir in provided dataset, it does not seem like a good idea to make the user click something on a map (he would need to find the water body first). With Daniel we discussed this briefly and we decided to "just" fetch the chart when the user clicks on the indicator in the left side list.
I am confident, we will still be able to include this to the release next week in the above outlined form (we have already the data in the database). Future evolution will be to make it for all water bodies, there we will need to rethink and reconsider the current approach, but clicking on individual ones on the map will be probably a way to go. Not implemented yet.

1) Yes, easily configurable.
2) Zoomed or aggregated? 
If aggregated: In principle they could be aggregated after fetching from the db, but we need to think how to convey the message to the user that on the map there is option to pick individual time entries, while on chart time series there are aggregates. I would suggest to create a separate issue to generalize and document expectations of this feature and how configurable it can be, ok ? 
If zoomed, this prevents to see trends and seasonality + we do not have a logic of restricting time in currently shown chart when the whole time array is larger. -> same as above, would need proper definition of what our goal is and then implement it
3) Yes, this should be easy, I think we have full OSM map as another layer, I will check and configure it as another optional baselayer.

**Comment by lubojr** [comment]
-> added 1: opacity 0.7 + 3 (our EOX rendered OSM layer as optional baselayer for all indicators) in this branch

Will leave 0 for separate PR

2 I would move to another issue after decision is made how to proceed

**Comment by lubojr** [comment]
-> separate issue for 2) created in https://github.com/eurodatacube/eodash/issues/2013

**Pull request merged**
