### PR TITLE
Species Information for IDEAS Wildlife

### PR DESCRIPTION
**Pull request by spectrachrome**
Screenshot 2024-04-19 at 16 29 27

### CODE REVIEW

**Review by lubojr — CHANGES_REQUESTED** [review]
@spectrachrome Thank you for the developments in this PR! 
I have updated the branch moving the JSON data to the bucket and fetching them from there instead of having it in this repo. I have additionally updated the used Wildlife raster for the current latest - EU-wide. I've set the longitudinal width by rule of thumb to 10 degrees for now. Can be still tweaked.

Functionality-wise this PR is already great but there are a few minor issues that we have not anticipated before seeing the integration with the EU-wide dataset and a few UI related issues.

- [ ] EU-wide dataset includes a lot of sea areas due to inclusion of Iceland. With today's seed for example it will end up in the middle of the atlantic ocean. Could we please include an optional configurable multipolygon mask - for example European main land + Iceland as a GeoJSON and check via intersection if the randomly checked bbox intersects this multipolygon mask? And if not, try choosing another seed deterministically depending on the original seed (adding some known character to it until it fits)?
- [ ] Could we include the list of species also to the "Lose scenario popup"?
- [ ] Species info in the DataPanel is very low and the panel needs to be scrolled. Could this be fixed?
- [ ] With larger areas selected there are species duplicates. Let's aggregate the results showing each species just once with an "english name" to the side of it and a count of how many times it appeared in the original listing.
- [ ] Let's add remaining mine count on the map there as well?

 Could you please have a look?

**Comment by spectrachrome** [comment]
Will take a look. Thank you for the review!

**Comment by spectrachrome** [comment]
The following things have been implemented and/or fixed 😊

- Minesweeper dialog now always renders local species, regardless of winning or losing the game.
- The user does not need to scroll down anymore to see the heading of the sidebar display and its first few species.
- Species duplicates are now aggregated with number chips next to their names
- A remaining mine counter has been added to the Minesweep controls. (Isn't this cheating?)

Just now I managed to get a small (181KB) low-resolution GeoJSON of common European countries, which I will now use to tackle the intersection testing and "altseed" generation in order to prevent water-only, instant-solve games.

**Review by lubojr — APPROVED** [review]
Looks great! Thank you! Merging!

**Pull request merged**
