### PR TITLE
Switch S5p data source

### LINKED ISSUE #447: Switch ESA NO2 data source from S5p-PAL to EDC
@JPatruno @gmilcinski 

create layer for TROPOMI NO2 maps 
update url in esa.js and trilateral.js for NO2 - TROPOMI global indicator (N1-ESA)

### PR DESCRIPTION
**Pull request by Schpidi**
Should fix #447 although the times (weekly, fortnightly, 2-daily) might need adjustments.

### CODE REVIEW

**Comment by aapopescu** [comment]
@Schpidi , is this still valid?

**Comment by Schpidi** [comment]
yes, this PR still needs to get merged if we want to switch to EDC and yes, the times need to be adjusted to the ones used in EDC unless the weekly update of 2-week intervals is kept.

**Comment by aapopescu** [comment]
> yes, this PR still needs to get merged if we want to switch to EDC and yes, the times need to be adjusted to the ones used in EDC unless the weekly update of 2-week intervals is kept.

The EDC still has the extra transparency issue. We need to resolve this before making the transition. Can you please have a look, @AlessandroScremin ?

**Comment by AlessandroScremin** [comment]
> > yes, this PR still needs to get merged if we want to switch to EDC and yes, the times need to be adjusted to the ones used in EDC unless the weekly update of 2-week intervals is kept.
> 
> The EDC still has the extra transparency issue. We need to resolve this before making the transition. Can you please have a look, @AlessandroScremin ?

The last time seems to be only a matter of time...now is transparency, could you please clarify the tranpsarency issue? I opened the staging and I don't understand the issue...

**Comment by aapopescu** [comment]
> > > yes, this PR still needs to get merged if we want to switch to EDC and yes, the times need to be adjusted to the ones used in EDC unless the weekly update of 2-week intervals is kept.
> > 
> > 
> > The EDC still has the extra transparency issue. We need to resolve this before making the transition. Can you please have a look, @AlessandroScremin ?
> 
> @Schpidi @aapopescu The last time seemed to be only a matter of time...now is transparency, could you please clarify the tranpsarency issue? I opened the staging and I don't understand the issue...

@AlessandroScremin , sorry if it wasn't clear, here are some more details. 
Currently in race.esa.int staging we get this view:
Screen Shot 2020-10-12 at 09 25 51
On the S5p-PAL we get this view:
Screen Shot 2020-10-12 at 09 25 31
And on the testing branch s5p we get this view (https://eodash-testing.eox.at/s5p/?poi=World-N1)
Screen Shot 2020-10-12 at 09 27 46

So, it looks like in PAL as well as in EDC there is an extra transparency

**Comment by AlessandroScremin** [comment]
> > > > yes, this PR still needs to get merged if we want to switch to EDC and yes, the times need to be adjusted to the ones used in EDC unless the weekly update of 2-week intervals is kept.
> > > 
> > > 
> > > The EDC still has the extra transparency issue. We need to resolve this before making the transition. Can you please have a look, @AlessandroScremin ?
> > 
> > 
> > @Schpidi @aapopescu The last time seemed to be only a matter of time...now is transparency, could you please clarify the tranpsarency issue? I opened the staging and I don't understand the issue...
> 
> @AlessandroScremin , sorry if it wasn't clear, here are some more details.
> Currently in race.esa.int staging we get this view:
> Screen Shot 2020-10-12 at 09 25 51
> On the S5p-PAL we get this view:
> Screen Shot 2020-10-12 at 09 25 31
> And on the testing branch s5p we get this view (https://eodash-testing.eox.at/s5p/?poi=World-N1)
> Screen Shot 2020-10-12 at 09 27 46
> 
> So, it looks like in PAL as well as in EDC there is an extra transparency

is it the same what I'm looking at?
image

**Comment by AlessandroScremin** [comment]
> > > > yes, this PR still needs to get merged if we want to switch to EDC and yes, the times need to be adjusted to the ones used in EDC unless the weekly update of 2-week intervals is kept.
> > > 
> > > 
> > > The EDC still has the extra transparency issue. We need to resolve this before making the transition. Can you please have a look, @AlessandroScremin ?
> > 
> > 
> > @Schpidi @aapopescu The last time seemed to be only a matter of time...now is transparency, could you please clarify the tranpsarency issue? I opened the staging and I don't understand the issue...
> 
> @AlessandroScremin , sorry if it wasn't clear, here are some more details.
> Currently in race.esa.int staging we get this view:
> Screen Shot 2020-10-12 at 09 25 51
> On the S5p-PAL we get this view:
> Screen Shot 2020-10-12 at 09 25 31
> And on the testing branch s5p we get this view (https://eodash-testing.eox.at/s5p/?poi=World-N1)
> Screen Shot 2020-10-12 at 09 27 46
> 
> So, it looks like in PAL as well as in EDC there is an extra transparency

DOn'have access to the testing platform  same user and owd I got access denied

**Comment by AlessandroScremin** [comment]
@aapopescu @Schpidi 

I played a bit with the layer visualisation settings...

Updated the custom script...COuld you pease give me feedbacks?

kr

Alessandro

**Comment by aapopescu** [comment]
> DOn'have access to the testing platform same user and owd I got access denied

Try going here and login with the usual credentials :
https://eodash-testing.eox.at/s5p/index.html

**Comment by aapopescu** [comment]
> @aapopescu @Schpidi
> 
> I played a bit with the layer visualisation settings...
> 
> Updated the custom script...COuld you pease give me feedbacks?
> 
> kr
> 
> Alessandro

@AlessandroScremin , looks much better. 
@Schpidi we can make the switch to EDC with this visualisation, thanks!

**Comment by AlessandroScremin** [comment]
From testin home page now I caould access

For teh visualisation perfect...I can work a bit with trasnpasrencies when needed...let see if also all other dates are fine....

**Comment by Schpidi** [comment]
@AlessandroScremin we're still using weekly updates of the 14-day intervals but I understand this is not what you're ingesting in EDC is it? should we switch to using only 14-day intervals?

**Comment by aapopescu** [comment]
> > @AlessandroScremin we're still using weekly updates of the 14-day intervals but I understand this is not what you're ingesting in EDC is it? should we switch to using only 14-day intervals?
> 
> This is what we are currently doing, if @aapopescu asks for the weekly updates of 14days interval we can implement the working chain...so far we are using the 14day interval

@AlessandroScremin, thanks! yes, let's mimic the s5p-PAL please

**Review by aapopescu — APPROVED** [review]
need to update to latest dates

**Comment by AlessandroScremin** [comment]
@aapopescu 
Yes, the fact is that they changed something at the source. A further clarification of the ingestion process request has been requested to ATOS in a Mail from Antonio Romeo sent out yesterday at 14.11 :  subject: Re: No2 data in EDC you in cc    (please read also the loop.

kr

ALessandro

**Comment by Schpidi** [comment]
What is the status here? Can we finally make the switch?

Note that we already use the EDC services for the draw functionality.

**Comment by Schpidi** [comment]
@AlessandroScremin any updates? Are the EDC services ready for production?

**Comment by AlessandroScremin** [comment]
> @AlessandroScremin any updates? Are the EDC services ready for production?

@Schpidi @aapopescu 
we are working in the integration of new data in EDC...the file names are changing...the information in the file are more and we are looking at them to udnertand how to use them (mainly inc ase of reprocessing)...and the frequency is not daily but random...every time they make a reporcessing the file is loaded with the cration date added to the file...saying that we already prepared the script and this morning we are reingesting all the data available in a new collection...then we check the visualisation if it is ok or need saome changes and then I can change the collection id to the configuration layer you are using...I will keep you updated

Ale

**Comment by lubojr** [comment]
times still dont match reality in edc, but otherwise ready to merge

**Pull request merged**
