### PR TITLE
Draw feature and truck indicator

### PR DESCRIPTION
**Pull request by Schpidi**
First implementation of #451. Should probably wait for all years of truck data to be ingested in geoDB.

### CODE REVIEW

**Comment by Schpidi** [comment]
Note that this also includes the "Unify indicators" feature (#500) as some fixes were present only in this branch.

**Comment by aapopescu** [comment]
> Note that this also includes the "Unify indicators" feature (#500) as some fixes were present only in this branch.

@silvester-pari, can you have a look at the [WIP] Unify indicators #548 to make sure the text is changeable? Alternatively, we need to fix the text in the subtitle and change the labels on the tabs

**Comment by Schpidi** [comment]
> > Note that this also includes the "Unify indicators" feature (#500) as some fixes were present only in this branch.
> 
> @silvester-pari, can you have a look at the [WIP] Unify indicators #548 to make sure the text is changeable? Alternatively, we need to fix the text in the subtitle and change the labels on the tabs

@aapopescu I'm going to revert the config for the unify indicators until we have a stable version.

**Comment by silvester-pari** [comment]
Thanks @Schpidi, the WIP pr is not ready for production (hence the name), but with a changed config it might work just fine, as the compare feature is not used...

**Comment by aapopescu** [comment]
Thank you, @Schpidi !

**Review by aapopescu — APPROVED** [review]

**Pull request merged**
