### PR TITLE
Create Contributors.md

### PR DESCRIPTION
**Pull request by aapopescu**

### CODE REVIEW

**Comment by Schpidi** [comment]
@Kampen1988 @gunbra32 this is the PR I mentioned last EDC call. please add people as you feel appropriate. this will be included in this week's Thursday release where will tag a new version as well to get a DOI from zenodo. thx

cc @gmilcinski

**Comment by aapopescu** [comment]
Missing Brockmann contributors , @gunbra32 can you please add?

**Review by Schpidi — APPROVED** [review]

**Comment by gunbra32** [comment]
I guess I am too late here.

**Comment by santilland** [comment]
Hello @gunbra32 however you prefer you can make a new pull request or send me or Stephan the list and we can update it.

**Comment by gunbra32** [comment]
[TonioF](https://github.com/TonioF) - **Tonio Fincke** - [BC](www.brockmann-consult.de)
[thomasstorm](https://github.com/thomasstorm) - **Thomas Storm** - [BC](www.brockmann-consult.de)

**Comment by santilland** [comment]
thank you @gunbra32 , I added it directly to the staging branch, will delete this branch now

**Pull request merged**
