### PR TITLE
homogenize fullscreen exit button and add "escape" button close evt

### PR DESCRIPTION
**Pull request by lubojr**

### CODE REVIEW

**Comment by lubojr** [comment]
@silvester-pari Can this one potentially cause trouble as in https://github.com/eurodatacube/eodash/issues/111 ? I dont fully understand the issue there.

**Comment by silvester-pari** [comment]
@lubojr i don't think this will be an issue, just make sure that the toolbar is flat (no shadow)

**Comment by lubojr** [comment]
Uff, wierd typo from IDE autosuggest. Thanks!

**Comment by silvester-pari** [comment]
So I think we agreed on not merging this. Maybe I find time to improve this otherwise, but should we close this for now?

**Comment by lubojr** [comment]
I would still very much like to see the escape button working, if we dont move the X.

**Comment by silvester-pari** [comment]
Agreed. Can you prepare such a modified pull request?

**Comment by Schpidi** [comment]
@lubojr can we delete this branch?

**Pull request closed without merging**
