### PR TITLE
Geodb generation implementation

### PR DESCRIPTION
**Pull request by santilland**
Make sure to change the submodule branch to master after merge

### CODE REVIEW

**Comment by Schpidi** [comment]
@AlessandroScremin @JPatruno please have look at the changes in the data like the times, also in https://github.com/eurodatacube/eodash-data/pull/152 and adjust the content of the geoDB if needed. Let us know anytime you want us to update the internal cache to review the changes made in geoDB.

**Comment by Schpidi** [comment]
@AlessandroScremin thanks for updating the data. Right now we're using the same table here for the trilateral version that you prepared for the race one. I guess we should use a separate one only containing BE03 and FR03 (note the slightly different ID instead of BE3 and FR3).

**Comment by Schpidi** [comment]
@AlessandroScremin ok, I extended the generation script to allow configuring a query. now we can retrieve E1 for trilateral and race from the same table. so from my point of view this is now ready for being merged to staging for final review. please approve this pr when you agree. thanks.

**Comment by AlessandroScremin** [comment]
Ok data are fine,
We have to add the last record for the 2020-08-30 that were in the last pull request but not in the GeoDB....

SO I approve this pull request...but add this comment to remmebr to update GeoDb

**Review by AlessandroScremin — APPROVED** [review]

**Pull request merged**
