### PR TITLE
Make global indicators button a panel that is open by default

### LINKED ISSUE #334: the selection box for global indicators might be confused with filters
no idea how to improve on this, but this was a feedback from users

### PR DESCRIPTION
**Pull request by komninoschat**
Fixes #334.

### CODE REVIEW

**Comment by silvester-pari** [comment]
@komninoschat This looks great! Only thing I would suggest is to start with the panel closed on mobile, as the screen space is quite limited - currently it starts opened.
On desktop, I think it's fine to start opened.

**Comment by silvester-pari** [comment]
@aapopescu when reviewing this, please also have a look at https://github.com/eurodatacube/eodash/issues/809#issuecomment-784183560 - we're not sure what is the best approach for displaying global data in the table, so we have three options there:
- keep country codes and only replace "all" (global) with globe icon (screenshot 1)
- use country flags and globe icon (screenshot 2)
- use country flags for countries and UNO/EU flags for global (screenshot 3)

**Comment by aapopescu** [comment]
@silvester-pari , trying to review but the eodash does not load, page gets stuck in loading

**Comment by aapopescu** [comment]
> @aapopescu when reviewing this, please also have a look at [#809 (comment)](https://github.com/eurodatacube/eodash/issues/809#issuecomment-784183560) - we're not sure what is the best approach for displaying global data in the table, so we have three options there:
> 
> * keep country codes and only replace "all" (global) with globe icon (screenshot 1)
> * use country flags and globe icon (screenshot 2)
> * use country flags for countries and UNO/EU flags for global (screenshot 3)

the screenshots are not visible, can you please add them?

**Comment by silvester-pari** [comment]
> > @aapopescu when reviewing this, please also have a look at [#809 (comment)](https://github.com/eurodatacube/eodash/issues/809#issuecomment-784183560) - we're not sure what is the best approach for displaying global data in the table, so we have three options there:
> > 
> > * keep country codes and only replace "all" (global) with globe icon (screenshot 1)
> > * use country flags and globe icon (screenshot 2)
> > * use country flags for countries and UNO/EU flags for global (screenshot 3)
> 
> the screenshots are not visible, can you please add them?

I'll have a look why it's not loading, sorry for that. The screenshots are located at https://github.com/eurodatacube/eodash/issues/809#issuecomment-784183560

**Comment by aapopescu** [comment]
> @aapopescu when reviewing this, please also have a look at [#809 (comment)](https://github.com/eurodatacube/eodash/issues/809#issuecomment-784183560) - we're not sure what is the best approach for displaying global data in the table, so we have three options there:
> 
> * keep country codes and only replace "all" (global) with globe icon (screenshot 1)
> * use country flags and globe icon (screenshot 2)
> * use country flags for countries and UNO/EU flags for global (screenshot 3)



> > > @aapopescu when reviewing this, please also have a look at [#809 (comment)](https://github.com/eurodatacube/eodash/issues/809#issuecomment-784183560) - we're not sure what is the best approach for displaying global data in the table, so we have three options there:
> > > 
> > > * keep country codes and only replace "all" (global) with globe icon (screenshot 1)
> > > * use country flags and globe icon (screenshot 2)
> > > * use country flags for countries and UNO/EU flags for global (screenshot 3)
> > 
> > 
> > the screenshots are not visible, can you please add them?
> 
> I'll have a look why it's not loading, sorry for that. The screenshots are located at [#809 (comment)](https://github.com/eurodatacube/eodash/issues/809#issuecomment-784183560)

Option 2 country flags + globe but can we use a colored globe icon as all the flags are coloured?

**Comment by silvester-pari** [comment]
Colored as in primary color? (black for trilateral as in screenshot, blue for ESA)
Or any other color?

**Comment by silvester-pari** [comment]
@aapopescu the feature branch should now work again, sorry for the inconvenience!

**Comment by aapopescu** [comment]
> Colored as in primary color? (black for trilateral as in screenshot, blue for ESA)
> Or any other color?

I was thinking of a regular Earth view, but it's your UI choice
image

**Comment by silvester-pari** [comment]
> > Colored as in primary color? (black for trilateral as in screenshot, blue for ESA)
> > Or any other color?
> 
> I was thinking of a regular Earth view, but it's your UI choice

We can do that, but then I would suggest replacing all globe icons (country filter, global indicators panel, table view). We'll look for a different globe icon though, that follow a more flat look (and doesn't focus so much on north america ;-) )

Something like this: https://www.iconfinder.com/icons/285647/globe_icon (although this icon is licensed under creative commons and we would have to fit the attribution somewhere).
image
image
image

It's a different style, then. The rest of the icons is very minimalistic and flat, as is the rest of the user interface, that might look too cartoonish.

**Review by aapopescu — APPROVED** [review]

**Pull request merged**
