### PR TITLE
2021 04 UI updates

### LINKED ISSUE #828: Map and graph side by side on maximised indicator panel
When right side panel is maximised, map covers all space and user might not realise there is something below the map.

What if we put side by side :
- the map
- the graph generated in e.g. trucks, airquality or mobility 
or 
-the map
- the story

### PR DESCRIPTION
**Pull request by santilland**
closes #828 and #888

### CODE REVIEW

**Comment by silvester-pari** [comment]
looking nice so far! here's some comments:

- [ ] there is some double scrollbar action going on in some screensizes (story/data panel)
- [ ] maybe we can make the close custom area chart button more prominent, as in maybe a arrow-left icon and text "back to area selection"?
- [ ] the custom area charts still overlap at the bottom, but it is fixed for normal charts
- [ ] mobility data: if a country is already selected, hide "(select country to load data)" under the title

**Comment by aapopescu** [comment]
Some more comments:

Custom AOI chart loading on top of map:
- [ ] drawing the AOI should trigger the processing instead of pushing the chart button; pushing the chart button should only load the chart 

COVID19 data and Trucks - Maps and Tabs behaviour:
Tab use is confusing because user has to select country /AOI twice to look at different charts. 
Two possible solutions:
- [ ] (not optimal) once a country/AOI is selected on one tab it should automatically be selected on the other tab too, so switching between tabs automatically changes the chart 
- [ ] (better) use tabs on charts instead of map; map selection is done once, both charts updated

**Comment by silvester-pari** [comment]
#888 has now been tackled in a separate PR: https://github.com/eurodatacube/eodash/pull/892
regarding tab switching consistency, this is now tracked in https://github.com/eurodatacube/eodash/issues/891

**Review by silvester-pari — APPROVED** [review]
Looks good to me, thanks Radu! Maybe @aapopescu also wants to have a look before merging.

**Comment by aapopescu** [comment]
COVID19 data https://eodash-testing.eox.at/2021-04-ui-updates/?poi=CV-CV 


**Current Behavior:**
Select one country in cases mode -> chart loads
Switch to Vaccinations tab
Switch back to Cases -> No data found for selection 

** Expected Behavior **
Select one country in cases mode -> chart loads
Switch to Vaccinations tab (country should be selected and chart should load automatically, but assuming at this stage it is still triggered by manual selection)
Switch back to Cases -> previous chart loads

**Pull request merged**
