### PR TITLE
E10a9 implementation

### PR DESCRIPTION
**Pull request by santilland**

### CODE REVIEW

**Comment by aapopescu** [comment]
Thanks, @AlessandroScremin @santilland , the visualisation is OK. 
Changes needed:


1. Description (how the indicator appears in the list):  ---> change to "Agricultural Workers"
2. "City" name to be corrected. Should be Apulia (not Apuleia)
3.  Categories to be updated:
- National Workers (aggregates all Italian worker categories)
- Foreign Workers (aggregates all Foreign worker categories)
- Unknown (aggregates all masked categories)

Story -  received from Sistema, Anca to add

**Comment by santilland** [comment]
@AlessandroScremin i think items 1 to 3 need to be changed in the data itself, could you take care of that?
As for point 4... i think we need to aggregate the provided array, so i guess this needs to be changed also in the data. So i imagine "just" adding the values of each categorie in a new group? So instead of having an array of 8 values, it should be an array with 3 values. Could you also take care of that Alessandro?

**Comment by AlessandroScremin** [comment]
@aapopescu @santilland 
If I understood well the point 3 is an option. so they would like to have all the values splitted but with the opossibility to aggregate them let say on demand...so we have to understand if creating new datasets with the aggregation or implement the aggregation like clikking on categories and makin the sum.

i will cotnact stefano to understand this.

**Comment by aapopescu** [comment]
> @aapopescu @santilland
> If I understood well the point 3 is an option. so they would like to have all the values splitted but with the opossibility to aggregate them let say on demand...so we have to understand if creating new datasets with the aggregation or implement the aggregation like clikking on categories and makin the sum.
> 
> i will cotnact stefano to understand this.

@AlessandroScremin, ok to talk to Stefano but we will not implement an additional feature to interact with the graphs.
I prefer to have the aggregation with just 3-5 categories.

**Review by aapopescu — APPROVED** [review]

**Pull request merged**
