### PR TITLE
Restructure GTIF drawer navigation menu and make breadcrumbs clickable

### LINKED ISSUE #1839: reorganize main menu

### LINKED ISSUE #1886: Make breadcrumbs interactive/clickable

### PR DESCRIPTION
**Pull request by spectrachrome**
Closes #1886
Closes #1839

### CODE REVIEW

**Comment by santilland** [comment]
image
@spectrachrome could you check how you do a line break in the menu if the name is too long?

**Review by santilland — CHANGES_REQUESTED** [review]
image
Please check how line breaks happens for long items

**Review by santilland — CHANGES_REQUESTED** [review]
Now that the breadcrumbs are visible in the explore mode again, they overlap when opening the submenu of the explore mode. See image below.
There is also a ticket to move the whole explore mode below the breadcrumbs navigation, that would fix the issue. I think it would be good to fix it in one go with this pull request.
image

**Comment by spectrachrome** [comment]
Currently working on this. Combining the PRs is a great idea. @santilland

**Comment by spectrachrome** [comment]
As discussed:

* Breadcrumbs now go across full page width and root crumb leads to home when clicked.
* Fix any overlapping between layout elements
* Text lines now break properly in menu items if they are too long.

Screenshot 2023-02-06 at 18 08 18

**Pull request merged**
