### PR TITLE
added data from Jaxa to be reviewed

### PR DESCRIPTION
**Pull request by AlessandroScremin**
Added the data from jaxa, but they provide only date and value, I filled all other fields, also SubAOI.
Please @aapopescu  have at llok to know if it is ok so.

### CODE REVIEW

**Comment by aapopescu** [comment]
story not visible for SG01-E9, maybe AOI_ID is configured as "sg" instead of "SG01"

**Comment by Schpidi** [comment]
there was a line with a wrong AOI_ID in the csv. fixed in the last commit

**Comment by Schpidi** [comment]
EO Data seems to be missing from the NASA API at least I can't find the right requests for the Tokyo indicator and the 2 most recent values for Singapore don't show data. any idea what I'm missing @drewbo ? Thanks

This works: https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/16/51673/32533@1x?url=s3%3A%2F%2Fcovid-eo-data%2Findustry%2Fsg_2020_05_30.tif&resampling_method=bilinear&bidx=1

This does not: https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/14/14423/6488@1x?url=s3%3A%2F%2Fcovid-eo-data%2Findustry%2Ftk_2020_06_13.tif&resampling_method=bilinear&bidx=1

**Comment by AlessandroScremin** [comment]
it is then the issue I opened before
https://github.com/eurodatacube/eodash/issues/408 

think can be closed

**Comment by Schpidi** [comment]
I'm merging this now and we'll update the eo data once available

**Comment by drewbo** [comment]
@Schpidi the industry data is only available in Singapore, up to 5/30

**Comment by AlessandroScremin** [comment]
I received this mail from @aapopescu  and you @Schpidi should have received it as well. Is it of help? maybe you miss it.

“New data for San Francisco water quality: 
- SPM: 

anomaly-spm-sf-2020_06_01.tif
anomaly-spm-sf-2020_06_03.tif
anomaly-spm-sf-2020_06_06.tif
anomaly-spm-sf-2020_06_13.tif
anomaly-spm-sf-2020_06_21.tif
anomaly-spm-sf-2020_06_22.tif
anomaly-spm-sf-2020_06_23.tif
anomaly-spm-sf-2020_06_25.tif
anomaly-spm-sf-2020_06_28.tif
anomaly-spm-sf-2020_06_3.tif
anomaly-spm-sf-2020_07_01.tif
anomaly-spm-sf-2020_07_03.tif 

- CHL-A: 

anomaly-chl-sf-2020_06_01.tif
anomaly-chl-sf-2020_06_03.tif
anomaly-chl-sf-2020_06_06.tif
anomaly-chl-sf-2020_06_13.tif
anomaly-chl-sf-2020_06_18.tif
anomaly-chl-sf-2020_06_21.tif
anomaly-chl-sf-2020_06_22.tif
anomaly-chl-sf-2020_06_23.tif
anomaly-chl-sf-2020_06_26.tif
anomaly-chl-sf-2020_06_28.tif
anomaly-chl-sf-2020_07_01.tif
anomaly-chl-sf-2020_07_03.tif
anomaly-chl-sf-2020_07_06.tif
anomaly-chl-sf-2020_07_08.tif
anomaly-chl-sf-2020_07_13.tif “


kr
ALe

**Comment by Schpidi** [comment]
for completeness, these are exactly the dates used in the update

**Comment by Schpidi** [comment]
> @Schpidi the industry data is only available in Singapore, up to 5/30

@drewbo so should we leave this as is, i.e. leave the last two entries in the CSV although there is no eo data or rather remove them?

**Comment by drewbo** [comment]
@Schpidi I'm not sure which CSV you're referring to but I would remove entries which don't have corresponding EO data

**Comment by Schpidi** [comment]
@drewbo referring to L11-12 https://github.com/eurodatacube/eodash/blob/staging/app/public/data/trilateral/E9.csv#L11

**Comment by drewbo** [comment]
ah, I'm not sure where that all derives from so could go either way

**Pull request merged**
