### PR TITLE
Intercept back button

### LINKED ISSUE #111: could we overwrite the back button to e.g. close the eo data modal

### PR DESCRIPTION
**Pull request by silvester-pari**
work in progress to fix #111

### CODE REVIEW

**Comment by silvester-pari** [comment]
Did some cleanup and testing, I believe it can be merged. Not all cases are covered where a back button might be expected, but I think most of them.
Should additional back button requirements arise, I would start a new branch.

**Review by Schpidi — APPROVED** [review]

**Comment by Schpidi** [comment]
@silvester-pari a minor comment, on mobile using the back button to close a selected poi I cannot select this same poi again afterwards.

**Comment by silvester-pari** [comment]
> @silvester-pari a minor comment, on mobile using the back button to close a selected poi I cannot select this same poi again afterwards.

good catch, thanks - i'll look into that!

**Comment by silvester-pari** [comment]
@Schpidi should be fixed in 58e6da6, now explicitly deselecting on mobile back button!

**Pull request merged**
